### ISSUE TITLE
tcp/ip implementation 

### ISSUE THREAD

**Issue by goRaspy** [skorokithakis/A6lib#1]
Hi, Could you precise  if your code let ESP connect the internet over the A6 GPRS connexion ?

**Comment by skorokithakis** [comment]
Sorry, I didn't see this until now (Github didn't subscribe me to issues, for some reason). Currently, the library can't connect to the internet, but I would love a PR adding that functionality.

**Comment by crosofg** [comment]
Has anyone added the GPRS Communication facility?

**Comment by skorokithakis** [comment]
It's in #5, but it's a huge PR so it takes time to review, alas.
