### ISSUE TITLE
Sms read problem

### ISSUE THREAD

**Issue by pusent** [skorokithakis/A6lib#10]
Getunreadsmslocs() not return value.
Readsms(3) function is working.
I changed cpp file in "rec unread" to "all" but nothing.
Where am i doing wrong?
i use arduino nano with a7 module.

**Comment by skorokithakis** [comment]
I'm afraid I can't really say what you're doing wrong without knowing anything about your code or what the problem is.

**Comment by pusent** [comment]
I do not have a special code. Using the sms in the library.

```
void loop() {
    callInfo cinfo = A6l.checkCallStatus();
    unreadSMSNum = A6l.getUnreadSMSLocs(unreadSMSLocs, 30);  // <<<< unreadSMSNum already return 0
   
        for (int i = 0; i < unreadSMSNum; i++) {
            Serial.print("New message at index: ");
            Serial.println(unreadSMSLocs[i], DEC);

            sms = A6l.readSMS(unreadSMSLocs[i]); // if i change like this A6l.readSMS(3). its running
            Serial.println(sms.number);
            Serial.println(sms.date);
            Serial.println(sms.message);
        }
        delay(1000);
}
```
I tried the following changes but I did not get a result;

 A6command("**AT+CNMI=1,0**", "OK", "yy", A6_CMD_TIMEOUT, 2, NULL); to >>>
 A6command("**AT+CNMI=0,2,0,0,0**", "OK", "yy", A6_CMD_TIMEOUT, 2, NULL);

if (A6_OK != A6command("**AT+CPMS=ME,ME,ME**", "OK", "yy", A6_CMD_TIMEOUT, 2, NULL)) to >>>
if (A6_OK != A6command("**AT+CPMS=SM,SM,SM**", "OK", "yy", A6_CMD_TIMEOUT, 2, NULL))

byte status = A6command("**AT+CMGL=\"REC UNREAD\"**", "\xff\r\nOK\r\n", "\r\nOK\r\n", A6_CMD_TIMEOUT, 2, &response); to >>>
byte status = A6command("**AT+CMGL=\"ALL\"**", "\xff\r\nOK\r\n", "\r\nOK\r\n", A6_CMD_TIMEOUT, 2, &response);

**Comment by skorokithakis** [comment]
Hmm, do you have any unread SMS?

**Comment by pusent** [comment]
Yes.. I am constantly sending new sms to modul.
I also use the underlying code.
AT+CMGL="ALL"
I guess I can not get the number of posts in mod

I also have a7 module, not a6. Could there be a change?

**Comment by skorokithakis** [comment]
Yes, this library is for the A6. What's the A7?

**Comment by pusent** [comment]
A7 same with a6 + gps module.

**Comment by crosofg** [comment]
Does A6 triggers a interrupt on receiving sms? Do I have to continuously check for unread SMS.. if I want to set a GPIO high of an attached microcontroller.

**Comment by skorokithakis** [comment]
It doesn't trigger an interrupt that I know of.

**Comment by crosofg** [comment]
How to know whether a message has been received? Do I have to keep checking
always?

**Comment by pusent** [comment]
Thank you for your interest.
I solved the problem.
The wait period required to read sms was not enough. I changed it to 5000.

byte status = A6command("AT+CMGL="REC UNREAD"", "\xff\r\nOK\r\n", "\r\nOK\r\n", 5000, 2, &response);

**Comment by skorokithakis** [comment]
Ah, great, i'm glad you figured it out!
