### ISSUE TITLE
Greek SIM

### ISSUE THREAD

**Issue by zstergios** [skorokithakis/A6lib#11]
I have you faced any issue with Greek SIM (cosmote/wind)?
Never connected.

Can you send me a pic with connections?

I tried also directly with Putty Serial Connection,

**Comment by skorokithakis** [comment]
Nope, works fine here. Maybe your antenna isn't connected properly?

**Comment by zstergios** [comment]
I have connected http://prntscr.com/ethcnp

There is non much documentation, so please help me:)
I have Arduino Uno, and if it will works I will connected on Pro Mini 2

My Pins
---------------
D0 to PIN2 
D5 to PIN0
D6 to PIN6
GNG to GNG
Power supplied by charger V5 and 2A

It's not responding, probably I have messed the pins

**Comment by skorokithakis** [comment]
I'm not sure, it's been a while. Have a look at [my schematic](https://gitlab.com/stavros/A6-ESP8266-breakout/) and connect it like that, it works.

**Comment by zstergios** [comment]
It's working. You have to wait at least 30seconds. It's OK.
Power Pin (D0) is the POWER KEY ? http://prntscr.com/evl31l
Because to turn of the module require to use the MOSFET with the Reset (RST) pin.
Am I missing something?

**Comment by skorokithakis** [comment]
I'm afraid I don't remember how I wired everything up, but the connections are in the schematic. You should drive a pin out to the MOSFET, which will provide power to the A6.
