### ISSUE TITLE
Problem with A6command. Passing quotes in the AT String

### ISSUE THREAD

**Issue by GeorgeDLake** [skorokithakis/A6lib#16]
Hi.
I need to pass user and password to the APN like this:
AT+CSTT="web.tmovil.cl","web","web"

but I dont seem to find how to do this.
Here is what I have tried:
retstatus=_A6l->A6command((const char *)"AT+CSTT=web.tmovil.cl,web,web", "OK", "yy", 20000, 1, NULL);
This will retrun:
Issuing command: AT+CSTT=web.tmovil.cl,web,web
Reply in 155 ms: 
OK
If I start adding quotes to the AT part of the line it still show the same Issuing Command.

**Comment by skorokithakis** [comment]
Escape your quotes?
