### ISSUE TITLE
sms:10: error: 'D6' was not declared in this scope   A6lib A6l(D6, D5);

### ISSUE THREAD

**Issue by ovisopa** [skorokithakis/A6lib#19]
Hello guys,

can you help me find out what I did wrong and why I get this error when veryfing the example sms sketch  ?

I'm using Arduino IDE 1.8.0 and now I also tried other examples and I get the same error.

What I'm doing wrong ? 

Thank you.

`sms:10: error: 'D6' was not declared in this scope

 A6lib A6l(D6, D5);
           ^
sms:10: error: 'D5' was not declared in this scope

 A6lib A6l(D6, D5);
               ^
E:\Google Drive\Software\arduino-1.8.0\libraries\A6lib\examples\sms\sms.ino: In function 'void setup()':

sms:22: error: 'D0' was not declared in this scope

     A6l.powerCycle(D0);
                    ^

E:\Google Drive\Software\arduino-1.8.0\libraries\A6lib\examples\sms\sms.ino: In function 'void loop()':

sms:29: error: request for member 'endsWith' in '"+1132352890"', which is of non-class type 'const char [12]'

         if ("+1132352890".endsWith(cinfo.number)) {
                           ^
sms:31: error: 'new_number' was not declared in this scope

             A6l.sendSMS(new_number, "I can't come to the phone right now, I'm a machine.");
                         ^

sms:48: error: expected '}' at end of input

     }

     ^

exit status 1
'D6' was not declared in this scope

`

**Comment by gnaeser** [comment]
Are you using an ESP? In that case you will need to fix some error in the example.
- The #ifndef on line 3 should be an #ifdef (and you will need to find out the gpio numbers for your specific type of ESP and modify D0, D5 and D6 accordingly).
- The phone number on line 29 needs to be cast to a String, ((String)"+1132352890").endsWith... or just define String myNumber = "+1132352890" and then use that with the .endsWith .
- Define newNumber, String newNumber = "555555555", or just give it inline.
- Add then missing closing } at the end of the file.

**Comment by skorokithakis** [comment]
I have fixed the mistakes in the example, thank you.

**Comment by ovisopa** [comment]
Thank you for fixing the example , now it compiles correctly ... but I now have an issue with the SIM provider, unfortunately this network **only supports 3G devices**, and my A6 it's only 2G. My only option is to buy a 3G module, as the other providers have only quite expensive SIM cards.

Thank you for fixing the exmple. Have a nice day!
