### ISSUE TITLE
Receive SMS

### ISSUE THREAD

**Issue by gerri3d** [skorokithakis/A6lib#21]
I wrote that lib in the Arduino IDE. Sending works fine but I can´t receive anything. only gibberish.

Issuing command: AT&F
REPLY:
OK
Reply in 56ms. Reply OK. <
OK
>
Issuing command: ATE0
REPLY: ATE0Å
OK
Reply in 55ms. Reply OK. <ATE0Å
OK
>
Issuing command: AT+CLIP=1
REPLY:
OK
⸮
Reply in 1055ms. Reply OK. <
OK
⸮>
Issuing command: AT+CMGF=1
REPLY:
OK
Reply in 55ms. Reply OK. <
OK
>
Issuing command: AT+CNMI=1,0
REPLY:
OK
Reply in 144ms. Reply OK. <
OK
>
Issuing command: AT+CPMS=ME,ME,ME
REPLY:
+CPMS: 21,2521,25,1,25
Reply in 202ms. Reply OK. <
+CPMS: 21,2521,25,1,25

OK
>

Issuing command: AT+CSCS="UCS2"
REPLY:
⸮OK
Reply in 56ms. Reply OK. <
⸮OK
>
Issuing command: AT+CSDH=1
REPLY:
OK
Reply in 58ms. Reply OK. <
OK
>

          Waiting for module to be ready...

Issuing command: AT+CMGL="ALL"
REPLY:
+CMGL:1,"REC READ",+4366306",,"2017/10/16,09:10:01+02",J⸮⸮⸮⸮⸮⸮Z⸮
Reply in 173ms. Reply OK. <
+CMGL:1,"REC READ",+4366306800",,"2017/10/16,09:10:01+02",J⸮⸮⸮⸮⸮⸮Z⸮>

Here the code
https://pastebin.com/fqCe3x9T

**Comment by skorokithakis** [comment]
Yes, the module does that sometimes. I'm afraid you're going to have to keep trying, as it's very finicky.
