### ISSUE TITLE
read sms issue

### ISSUE THREAD

**Issue by Saurman** [skorokithakis/A6lib#23]
Hello, I am using Arduino A6 GSM module (Ai-Thinker) and having a weird problem that I cannot resolve. After reading first incoming SMS module stops responding to further read sms commands with timeout error. I can provide dump if that helps. Please advice

**Comment by skorokithakis** [comment]
Unfortunately, this seems to be a common problem, as the A6 chip is a bit finicky. I can only advise you to check your power supply and serial lines, apart from that I can't offer much help. Do let me know if you get this fixed, though!
