### ISSUE TITLE
ESP32 BLE SCAN iBeacon data Advertised Device: Name: , Address: 76:b8:73:d7:d1:e9, manufacturer data: 4c00021502a9bada606c4865b2d4129ff22e82b300000000bf 

### ISSUE THREAD

**Issue by Shiro7** [skorokithakis/A6lib#40]
When I scan I got just those data but I know there is many other types of data when scan iBeacon with ESP32 I want to know how to get those data like signal power

**Comment by skorokithakis** [comment]
I am not quite sure what BLE has to do with this library.
