### ISSUE TITLE
 INVALID_PDU 304 error for int getUnreadSMSLocs(). what problem here? please assist me 

### ISSUE THREAD

**Issue by amit524** [skorokithakis/A6lib#7]
int getUnreadSMSLocs(int* buf, int maxItems) 
{
    String seqStart = "+CMGL: ";
    String response = "";

    // Issue the command and wait for the response.
    byte status = A6command("AT+CMGL=\"REC UNREAD\"", "\xff\r\nOK\r\n", "\r\nOK\r\n", A6_CMD_TIMEOUT, 2, &response);

    int seqStartLen = seqStart.length();
    int responseLen = response.length();
    int index, occurrences = 0;

    // Start looking for the +CMGL string.
    for (int i = 0; i < (responseLen - seqStartLen); i++) {
        // If we found a response and it's less than occurrences, add it.
        if (response.substring(i, i + seqStartLen) == seqStart && occurrences < maxItems) {
            // Parse the position out of the reply.
            sscanf(response.substring(i, i + 12).c_str(), "+CMGL: %u,%*s", &index);

            buf[occurrences] = index;
            occurrences++;
        }
    }
    return occurrences;
}

**Comment by skorokithakis** [comment]
I don't understand this. Please elaborate on the problem with steps to reproduce.

**Comment by amit524** [comment]
when i exucte getUnreadSMSLocs(int* buf, int maxItems) this function i getting time out error
 or 
 A6command("AT+CMGL=\"REC UNREAD\"", "\xff\r\nOK\r\n", "\r\nOK\r\n", A6_CMD_TIMEOUT, 2, &response);
changed function "AT+CMGL=0" inplace of "AT+CMGL=\"REC UNREAD\""
 A6command("AT+CMGL=0", "\xff\r\nOK\r\n", "\r\nOK\r\n", A6_CMD_TIMEOUT, 2, &response);

**Comment by skorokithakis** [comment]
Did that work?

**Comment by amit524** [comment]
no 

+CMS ERROR: 304 Invalid PDU mode parameter  comes

and other all function work  properly

**Comment by skorokithakis** [comment]
So the problem is that you're getting a timeout when trying to read SMS with `getUnreadSMSLocs`?

**Comment by amit524** [comment]
i am using hardware serial inplace of software serial and using mega 2560

**Comment by amit524** [comment]
yes if i increase #define A6_CMD_TIMEOUT 2000 then also time out error or +CMS ERROR: 304  comes

**Comment by skorokithakis** [comment]
Hmm, that's odd. Can you try setting SMS to text mode again?

```
A6command("AT+CMGF=1", "OK", "yy", A6_CMD_TIMEOUT, 2, NULL);
```

**Comment by amit524** [comment]
this is my cade

callInfo cinfo = checkCallStatus();
  if (cinfo.direction == DIR_INCOMING) 
    {
      Serial.println(cinfo.number);
      hangUp();
 unreadSMSNum =getUnreadSMSLocs(unreadSMSLocs, 30); 
 Serial.println("unreadSMSNum"); 
 Serial.println(unreadSMSNum); 
 for (int i = 0; i < unreadSMSNum; i++)
       {
            Serial.print("New message at index: ");
            Serial.println(unreadSMSLocs[i], DEC);

            sms =readSMS(unreadSMSLocs[i]);
            Serial.println(sms.number);
            Serial.println(sms.date);
            Serial.println(sms.message);
        }
    }

**Comment by skorokithakis** [comment]
Does SMS work after that?

**Comment by amit524** [comment]
now its work 
responce like this

Timed out.
Issuing command: ATH
Reply in 1055 ms: 
OK

Reply OK.
Issuing command: AT+CMGF=1
Reply in 1055 ms: 
OK

Reply OK.
Issuing command: AT+CMGL="REC UNREAD"
Reply in 1058 ms: 
OK

Reply OK.
unreadSMSNum
0
Issuing command: AT+CLCC
Reply in 1055 ms: 
OK

**Comment by amit524** [comment]
but every time i got the unreadSMSNum is 0

**Comment by amit524** [comment]
and not enter in this loop

for (int i = 0; i < unreadSMSNum; i++)
       {
            Serial.print("New message at index: ");
            Serial.println(unreadSMSLocs[i], DEC);

            sms =readSMS(unreadSMSLocs[i]);
            Serial.println(sms.number);
            Serial.println(sms.date);
            Serial.println(sms.message);
        }

**Comment by amit524** [comment]
if i send the new message then also reponce like
Reply OK.
Issuing command: AT+CMGF=1
Reply in 1055 ms:
OK

Reply OK.
Issuing command: AT+CMGL="REC UNREAD"
Reply in 1058 ms:
OK

Reply OK.
unreadSMSNum
0
Issuing command: AT+CLCC
Reply in 1055 ms:
OK
