### ISSUE TITLE
MODULE SIM TO SHARE INTERNET?

### ISSUE THREAD

**Issue by TronikMecatron** [skorokithakis/A6lib#9]
Hello, I have visited the page very often, obtaining very good results and always taking my knowledge.

Now something occurred to me and I still do not find anything concrete. My question is the following ... Is it possible to use any of the SIM modules to use the data that has the microSIM, and that way to connect to the internet, just as we do when sharing the internet with the cell phone?

I think it should be activating this function using AT command but before moving something, I prefer to make sure, besides I do not know if I have to add the WIFIesp8266 to transmit this data. Thank you and a big greeting, even if I do it before, I will not hesitate to share it with the community.

**Comment by skorokithakis** [comment]
Yes, there is, it's in PR #5, but I've been remiss in reviewing it, sadly...
